// OG-card lookup (P12) — the per-route share cards live in public/og/
// (generated by scripts/gen-og-cards.mjs from the real pages, committed as
// release assets). Pages resolve their card through this helper instead of
// hardcoding the path so a missing/deleted card degrades to BaseHead's
// sitewide og-default.png instead of shipping a broken og:image URL.
//
// Build-time only: this runs in Astro frontmatter during SSG (Node), never in
// the client bundle. The public/ probe assumes the build runs from the project
// root (the same assumption astro.config.mjs itself makes).
import { existsSync } from 'node:fs';
import { resolve } from 'node:path';

/**
 * Path (relative to public/, the shape BaseHead's ogImage prop takes) of the
 * generated card for a route/post name, or undefined when no card exists so
 * the caller falls back to the sitewide default.
 *
 * Names match the gen-og-cards.mjs inventory: 'home', 'projects', 'writing',
 * 'graveyard', 'behind-the-build', 'about', 'contact', and 'post-<slug>'.
 */
export function ogCardFor(name: string): string | undefined {
  const file = resolve(process.cwd(), 'public/og', `${name}.png`);
  return existsSync(file) ? `og/${name}.png` : undefined;
}
