import { test, expect } from './test-base';
import { ALL_ROUTES } from './routes';

// OG-card contract over HTTP (P12): every route advertises a ROUTE-SPECIFIC
// share card (public/og/*, generated by scripts/gen-og-cards.mjs) and the
// advertised URL actually serves an image of share-crawler-friendly weight.
// Dimensions + the exact 1200×630 canvas are asserted offline against dist by
// scripts/check-og-cards.mjs (sharp probe — cheaper and more precise than
// decoding in the browser); this spec owns the served-over-HTTP half.

const OG_MAX_BYTES = 300 * 1024;

for (const route of ALL_ROUTES) {
  test(`og card ${route}`, async ({ page, request, baseURL }) => {
    await page.goto(route, { waitUntil: 'domcontentloaded' });

    const ogImage = await page
      .locator('meta[property="og:image"]')
      .getAttribute('content');
    expect(ogImage, `og:image present on ${route}`).toBeTruthy();
    // Route-specific card, not the sitewide default (no post overrides its
    // card via frontmatter today; if one ever does, it still must resolve).
    expect(ogImage, `route-specific card on ${route}`).toContain('/og/');

    // twitter:image mirrors og:image (both emitted from BaseHead's one prop).
    await expect(page.locator('meta[name="twitter:image"]')).toHaveAttribute(
      'content',
      ogImage!,
    );

    // The advertised URL is absolute against the production origin; fetch the
    // same path from the preview server under test.
    const path = new URL(ogImage!).pathname;
    const res = await request.get(new URL(path, baseURL).href);
    expect(res.status(), `og:image fetch for ${route}`).toBe(200);
    expect(res.headers()['content-type']).toContain('image/png');
    const body = await res.body();
    expect(body.byteLength, `card weight for ${route}`).toBeLessThanOrEqual(OG_MAX_BYTES);
  });
}
